### ISSUE TITLE
DefaultValue attribute property rename

### ISSUE THREAD

**Issue by gsscoder** [gsscoder/commandline#179]
Since 2.0.x-pre breaks with past stable, at least _until 2.0.x reach beta_ some breaking change could be done to public API.

Add like to do what in subject. Instead of:
```csharp
[Option(DefaultValue = "中文",
    HelpText = "Content language.")]
  public Language { get; set; }
```
to:
```csharp
[Option(Default = "中文",
    HelpText = "Content language.")]
  public Language { get; set; }
```

Opinions?

cc/ @mizipzor @nemec @gimmemoore

**Comment by nemec** [comment]
I think they're both equally clear, and this change would distance itself from the `MetaValue` property which is not at all related to `DefaultValue`. It would also reduce repetition in `ValueAttribute`. No more `[Value(DefaultValue=[...])]`

+1

**Comment by gsscoder** [comment]
@nemec, thanks for clear comment... I thought only to shortening property name, but you added valuable points!

**Comment by gsscoder** [comment]
Done.

**Comment by XenHat** [comment]
I've been putting off updating CommandLine for our project because I was unaware of this rename and I thought the option had been removed:
![image](https://cloud.githubusercontent.com/assets/980408/26746273/7fd4eee8-47bc-11e7-9d14-5b950aea9f10.png)

I also couldn't find any indication of that option still existing in the documentation until I started searching through the closed issues.
Perhaps documentation on how to specify default values should be re-added for LatestVersion?
